apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage

data:
  settings.yaml: |
    title: Homelab

  services.yaml: |
    - Infrastructure:
        - Kubernetes:
            description: Homelab Kubernetes Cluster

  kubernetes.yaml: |
    mode: cluster

  widgets.yaml: |
    []

  bookmarks.yaml: |
    []

  docker.yaml: |
    {}

  proxmox.yaml: |
    {}

  custom.css: ""

  custom.js: ""
